### ISSUE TITLE
Handling of empty masks in hd95

### ISSUE THREAD

**Issue by ykirchhoff** [AImageLab-zip/ToothFairy#5]
Hi,

the current handling of empty masks in the [Hausdorff distance](https://github.com/AImageLab-zip/ToothFairy/blob/main/ToothFairy2/evaluation/evaluation.py#L50) might lead to unwanted behavior. If only the ground truth or the prediction are empty a worst possible value (e.g. the diagonal of the volume) should be assigned and only if both are empty it should be set to 0. Otherwise a false prediction might be assigned the best possible score of 0.

Best,
Yannick

**Comment by LucaLumetti** [comment]
Hi Yannick,

We've been discussing the matter already this morning and agree with your suggestion. The original decision was based on the code from a well-known paper, and I initially trusted their judgment without question. However, I've since reconsidered, and I'll be updating it soon to return the diagonal of the volume.

Best,
Luca
